export const UI_TEXT = {
  LOGIN: {
    TITLE: "Welcome back",
    SUBTITLE: "Sign in to your account",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "you@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT_BUTTON: "Sign In",
    NO_ACCOUNT: "Don't have an account?",
    SIGNUP_LINK: "Sign up",
  },
  SIGNUP: {
    TITLE: "Create your account",
    SUBTITLE: "Get started with your company careers page",
    COMPANY_NAME_LABEL: "Company Name",
    COMPANY_NAME_PLACEHOLDER: "Acme Inc.",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "you@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    SUBMIT_BUTTON: "Create Account",
    HAVE_ACCOUNT: "Already have an account?",
    LOGIN_LINK: "Sign in",
  },
  HOME: {
    SUBTITLE: "Manage your careers page and attract top talent",
    LOGOUT_BUTTON: "Logout",
    STATS: {
      BEAUTIFUL_DESIGN_TITLE: "Beautiful Design",
      BEAUTIFUL_DESIGN_DESC: "Create stunning career pages",
      QUICK_SETUP_TITLE: "Quick Setup",
      QUICK_SETUP_DESC: "Get started in minutes",
      ATTRACT_TALENT_TITLE: "Attract Talent",
      ATTRACT_TALENT_DESC: "Build your dream team",
    },
    CAREERS_PAGE: {
      TITLE: "Your Careers Page",
      VIEW_BUTTON: "View",
      COPY_BUTTON: "Copy Link",
      COPIED_BUTTON: "Copied!",
    },
    CUSTOMIZE: {
      TITLE: "Customize Your Careers Page",
      DESCRIPTION: "Update your company branding, add content sections, and showcase your culture to attract the best candidates.",
      BUTTON: "Edit Company Details",
    },
    TOAST: {
      COPY_SUCCESS: "Careers page link copied to clipboard!",
      COPY_ERROR: "Failed to copy link",
    },
  },
  COMPANY_SETTINGS: {
    TITLE: "Company Settings",
    SUBTITLE: "Manage your company profile and branding",
    BACK_BUTTON: "Back to Home",
    LOADING: "Loading company settings...",
    SECTIONS: {
      COMPANY_DETAILS: "Company Details",
      BRAND_THEME: "Brand Theme",
      CULTURE: "Culture",
      BENEFITS: "Why Join Us Benefits (Required: 3 cards)",
      BENEFITS_DESC: "Add three benefit cards that will be displayed on your careers page.",
      CONTENT_SECTIONS: "Content Sections",
      NO_SECTIONS: "No content sections yet. Click \"Add Section\" to create one.",
    },
    LABELS: {
      COMPANY_NAME: "Company Name",
      COMPANY_TAGLINE: "Company Tagline",
      LOGO_URL: "Logo URL",
      BANNER_URL: "Banner Image URL",
      PRIMARY_COLOR: "Primary Color",
      CULTURE_VIDEO_URL: "Culture Video URL",
      BENEFIT_CARD: "Benefit Card",
      TITLE: "Title",
      DESCRIPTION: "Description",
    },
    PLACEHOLDERS: {
      COMPANY_NAME: "Acme Inc.",
      TAGLINE: "Building the future, one hire at a time",
      LOGO_URL: "https://example.com/logo.png",
      BANNER_URL: "https://example.com/banner.jpg",
      VIDEO_URL: "https://youtube.com/watch?v=...",
      BENEFIT_TITLE: "Innovation First",
      BENEFIT_DESC: "Work on cutting-edge projects that push boundaries",
    },
    BUTTONS: {
      ADD_SECTION: "Add Section",
      SAVE_CHANGES: "Save Changes",
      PREVIEW: "Preview",
    },
    PREVIEW_DEFAULTS: {
      COMPANY_NAME: "Your Company",
    },
  },
  CAREERS_PAGE: {
    HERO: {
      TITLE_PREFIX: "Careers at",
      FALLBACK_NAME: "Company",
      VIEW_ROLES_BUTTON: "View Open Roles",
      ARIA_LABEL: "Scroll to open job positions",
    },
    BENEFITS: {
      TITLE_PREFIX: "Why Join",
      TITLE_SUFFIX: "?",
      FALLBACK_NAME: "Us",
      SUBTITLE: "Be part of something extraordinary",
    },
    CULTURE: {
      TITLE_PREFIX: "Life at",
      FALLBACK_NAME: "Company",
      SUBTITLE: "See what it's like to be part of our team",
      VIDEO_NOT_SUPPORTED: "Your browser does not support the video tag.",
    },
    JOBS: {
      TITLE: "Open Roles",
      SUBTITLE: "Find your perfect role and start your journey with us",
    },
    FOOTER: {
      COPYRIGHT: "All rights reserved.",
      FALLBACK_NAME: "Company",
      TAGLINE: "Building the future, one hire at a time.",
    },
  },
} as const;
